#!/usr/bin/python

VERSION='0.0.1'
APPNAME='test'
srcdir = './'
blddir = 'build'

def set_options(opt):
	opt.tool_options('compiler_cxx')

def init():
	print '\nInitializing CustomGtkmmWidgetArea build...'

def configure(conf):
	print 'Configuring the build enviroment...'
	conf.check_tool	('compiler_cxx')
	
	conf.check_cfg	(package='gtkmm-2.4',args='--cflags --libs',uselib_store='GTKMM')
	
	# Default to a debug build
	conf.env.append_value('CXXFLAGS', ['-O2', '-g','-Wall'])

def build(bld):
	print '\nBuilding the sources to objects...'
	
	canObj = bld.new_task_gen(
		features	= 'cxx cstaticlib',
		source		= 'canvasobject.cpp',
		uselib		= 'GTKMM',
		target		= 'canobj' )
	
	jacklabel = bld.new_task_gen(
		features	= 'cxx cstaticlib',
		source		= 'modularcanvas.cpp',
		uselib		= 'GTKMM',
		uselib_local= 'canobj',
		target		= 'modcan' )
	
	main = bld.new_task_gen(
		features	= 'cxx cprogram',
		source		= 'main.cpp',
		uselib		= 'GTKMM',
		uselib_local= 'modcan',
		target		= 'main')
	


def shutdown():
	print('')
